/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Jun 26, 2011, 7:17:04 PM
 */
package com.maquant;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author mario
 */
public class Main extends javax.swing.JFrame {
    
    private int splines = 1;
    private boolean paused = false;

    /** Creates new form Main */
    public Main() {
        initComponents();
        ((SpinnerNumberModel)splineControlSpinner.getModel()).setMaximum(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addPointButton = new javax.swing.JButton();
        removePointButton = new javax.swing.JButton();
        playPauseButton = new javax.swing.JButton();
        addShadowButton = new javax.swing.JButton();
        removeShadowButton = new javax.swing.JButton();
        splineControlSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        addSplineButton = new javax.swing.JButton();
        removeSplineButton = new javax.swing.JButton();
        splineJPanel = new SplinesJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addPointButton.setText("Añadir Punto");
        addPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPointButtonActionPerformed(evt);
            }
        });

        removePointButton.setText("Remover Punto");
        removePointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePointButtonActionPerformed(evt);
            }
        });

        playPauseButton.setText("Pausa");
        playPauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPauseButtonActionPerformed(evt);
            }
        });

        addShadowButton.setText("Añadir Sombra");
        addShadowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShadowButtonActionPerformed(evt);
            }
        });

        removeShadowButton.setText("Remover Sombra");
        removeShadowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeShadowButtonActionPerformed(evt);
            }
        });

        splineControlSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));

        jLabel2.setText("Controlar Spline:");

        addSplineButton.setText("Añadir Spline");
        addSplineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSplineButtonActionPerformed(evt);
            }
        });

        removeSplineButton.setText("Remover Spline");
        removeSplineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSplineButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(addPointButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(removePointButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addShadowButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(removeShadowButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addSplineButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(removeSplineButton)
                .add(62, 62, 62)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(splineControlSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(playPauseButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(addPointButton)
                        .add(removePointButton)
                        .add(addShadowButton)
                        .add(removeShadowButton)
                        .add(addSplineButton)
                        .add(removeSplineButton))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(playPauseButton)
                        .add(jLabel2))
                    .add(splineControlSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splineJPanel.setBackground(new java.awt.Color(0, 0, 0));
        splineJPanel.setForeground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout splineJPanelLayout = new org.jdesktop.layout.GroupLayout(splineJPanel);
        splineJPanel.setLayout(splineJPanelLayout);
        splineJPanelLayout.setHorizontalGroup(
            splineJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1120, Short.MAX_VALUE)
        );
        splineJPanelLayout.setVerticalGroup(
            splineJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 599, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(splineJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(splineJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPointButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).addPoint(Integer.parseInt(splineControlSpinner.getValue().toString()));
    }//GEN-LAST:event_addPointButtonActionPerformed

    private void removePointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePointButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).removePoint(Integer.parseInt(splineControlSpinner.getValue().toString()));
    }//GEN-LAST:event_removePointButtonActionPerformed

    private void playPauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPauseButtonActionPerformed
        if (!paused) {
            ((SplinesJPanel)this.splineJPanel).pause();
            paused = true;
            playPauseButton.setText("Continuar");
        }
        else {
            ((SplinesJPanel)this.splineJPanel).play();
            paused = false;
            playPauseButton.setText("Pausa");
        }
    }//GEN-LAST:event_playPauseButtonActionPerformed

    private void addShadowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShadowButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).addShadow();
    }//GEN-LAST:event_addShadowButtonActionPerformed

    private void removeShadowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeShadowButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).removeShadow();
    }//GEN-LAST:event_removeShadowButtonActionPerformed

    private void addSplineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSplineButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).addSpline();
        splines++;
        ((SpinnerNumberModel)splineControlSpinner.getModel()).setMaximum(splines-1);
        ((SpinnerNumberModel)splineControlSpinner.getModel()).setValue(((SpinnerNumberModel)splineControlSpinner.getModel()).getNextValue());
    }//GEN-LAST:event_addSplineButtonActionPerformed

    private void removeSplineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSplineButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).removeSpline();
        splines--;
        ((SpinnerNumberModel)splineControlSpinner.getModel()).setMaximum(splines-1);
        ((SpinnerNumberModel)splineControlSpinner.getModel()).setValue(((SpinnerNumberModel)splineControlSpinner.getModel()).getMaximum());
    }//GEN-LAST:event_removeSplineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPointButton;
    private javax.swing.JButton addShadowButton;
    private javax.swing.JButton addSplineButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playPauseButton;
    private javax.swing.JButton removePointButton;
    private javax.swing.JButton removeShadowButton;
    private javax.swing.JButton removeSplineButton;
    private javax.swing.JSpinner splineControlSpinner;
    private javax.swing.JPanel splineJPanel;
    // End of variables declaration//GEN-END:variables
}
