/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Jun 26, 2011, 7:17:04 PM
 */
package com.maquant;

/**
 *
 * @author mario
 */
public class Main extends javax.swing.JFrame {
    
    private int pointQuantity = 10;
    private boolean paused = false;

    /** Creates new form Main */
    public Main() {
        initComponents();
        pointQuantityField.setText(String.valueOf(pointQuantity));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addPointButton = new javax.swing.JButton();
        removePointButton = new javax.swing.JButton();
        pointQuantityField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        playPauseButton = new javax.swing.JButton();
        addShadowButton = new javax.swing.JButton();
        removeShadowButton = new javax.swing.JButton();
        splineJPanel = new SplinesJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addPointButton.setText("Añadir Punto");
        addPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPointButtonActionPerformed(evt);
            }
        });

        removePointButton.setText("Remover Punto");
        removePointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePointButtonActionPerformed(evt);
            }
        });

        pointQuantityField.setMinimumSize(new java.awt.Dimension(54, 28));
        pointQuantityField.setPreferredSize(new java.awt.Dimension(54, 28));

        jLabel1.setText("# Puntos:");

        playPauseButton.setText("Pausa");
        playPauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPauseButtonActionPerformed(evt);
            }
        });

        addShadowButton.setText("Añadir Sombra");
        addShadowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShadowButtonActionPerformed(evt);
            }
        });

        removeShadowButton.setText("Remover Sombra");
        removeShadowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeShadowButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(addPointButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(removePointButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addShadowButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(removeShadowButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 113, Short.MAX_VALUE)
                .add(playPauseButton)
                .add(18, 18, 18)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pointQuantityField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addPointButton)
                    .add(removePointButton)
                    .add(pointQuantityField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(playPauseButton)
                    .add(addShadowButton)
                    .add(removeShadowButton))
                .addContainerGap(0, Short.MAX_VALUE))
        );

        splineJPanel.setBackground(new java.awt.Color(0, 0, 0));
        splineJPanel.setForeground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout splineJPanelLayout = new org.jdesktop.layout.GroupLayout(splineJPanel);
        splineJPanel.setLayout(splineJPanelLayout);
        splineJPanelLayout.setHorizontalGroup(
            splineJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 888, Short.MAX_VALUE)
        );
        splineJPanelLayout.setVerticalGroup(
            splineJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 584, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(splineJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(splineJPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPointButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).addPoint();
        pointQuantity+= 1;
        pointQuantityField.setText(String.valueOf(pointQuantity));
    }//GEN-LAST:event_addPointButtonActionPerformed

    private void removePointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePointButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).removePoint();
        pointQuantity-= 1;
        pointQuantityField.setText(String.valueOf(pointQuantity));
    }//GEN-LAST:event_removePointButtonActionPerformed

    private void playPauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPauseButtonActionPerformed
        if (!paused) {
            ((SplinesJPanel)this.splineJPanel).pause();
            paused = true;
            playPauseButton.setText("Continuar");
        }
        else {
            ((SplinesJPanel)this.splineJPanel).play();
            paused = false;
            playPauseButton.setText("Pausa");
        }
    }//GEN-LAST:event_playPauseButtonActionPerformed

    private void addShadowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShadowButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).addShadow();
    }//GEN-LAST:event_addShadowButtonActionPerformed

    private void removeShadowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeShadowButtonActionPerformed
        ((SplinesJPanel)this.splineJPanel).removeShadow();
    }//GEN-LAST:event_removeShadowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPointButton;
    private javax.swing.JButton addShadowButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playPauseButton;
    private javax.swing.JTextField pointQuantityField;
    private javax.swing.JButton removePointButton;
    private javax.swing.JButton removeShadowButton;
    private javax.swing.JPanel splineJPanel;
    // End of variables declaration//GEN-END:variables
}
